name: Manual Build REasy

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Match your Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run build.bat
      shell: cmd
      run: build.bat

    - name: Install WinRAR (portable CLI)
      run: |
        Invoke-WebRequest https://www.rarlab.com/rar/rarx64.exe -OutFile rar.exe
        Start-Process -Wait -FilePath .\rar.exe /S

    - name: Create REasy.rar
      run: |
        "C:\Program Files\WinRAR\WinRAR.exe" a REasy.rar dist\REasy_x64.exe

    - name: Upload artifact (REasy.rar)
      uses: actions/upload-artifact@v4
      with:
        name: REasy Build (RAR)
        path: REasy.rar
