name: Build and Package REasy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

  release:
    types: [published]

permissions:
  id-token: write     
  attestations: write   
  contents: write      

jobs:
  build-windows:
    runs-on: windows-latest
    environment: REasy ENV

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    
    - name: Run build.bat
      shell: cmd
      run: build.bat
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@v2.4.0
      with:
        subject-path: dist/REasy_x64.exe

    - name: Determine version
      id: get_version
      run: |
        if ($env:GITHUB_EVENT_NAME -eq "release") {
          $version = "${{ github.event.release.tag_name }}"
        } else {
          $input_version = "${{ github.event.inputs.version }}"
          if ($input_version -like "v*") {
            $version = $input_version
          } else {
            $version = "v$input_version"
          }
        }
        echo "version=$version" >> $env:GITHUB_ENV

    - name: Create ZIP archive
      run: |
        Compress-Archive -Path .\dist\* -DestinationPath "REasy $env:version.zip"

    - name: Upload ZIP to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "REasy ${{ env.version }}"
        tag_name: "${{ env.version }}"
        files: "REasy ${{ env.version }}.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: reasy-${{ env.version }}
        path: "REasy ${{ env.version }}.zip"
